### PR TITLE
Web socket reconnect failure #643

### LINKED ISSUE #643: Web Socket Reconnect failure
After 5 minutes the server closes the web socket if it does not read nor write a byte on the connection.
However, the client attempts to reconnect and is failing because URL is undefined
Within the setInterval (see screen grab below) in WbeSocketConnector.js function, the `this` object does not have the URL property defined

image

### PR DESCRIPTION
**Pull request by mdhsl**

### CODE REVIEW

File: source/core/datasource/handler/TimeSeriesDataSourceHandler.js [hunk 1]
```diff
@@ -22,12 +22,13 @@ class TimeSeriesDataSourceHandler extends DataSourceHandler {
...
         const lastStartTimeCst = this.parser && this.lastStartTime || properties.startTime;
+        const endpoint = properties.protocol + '://' + properties.endpointUrl;
+
         this.connector.onReconnect = () => {
             // if not real time, preserve last timestamp to reconnect at the last time received
             // for that, we update the URL with the new last time received
             if (lastStartTimeCst !== 'now') {
-                this.connector.setUrl(this.parser.buildUrl(
-                    {
+                this.connector.setUrl(endpoint + '?' + this.parser.buildUrl({
```
Comment (nickgaray) [inline source/core/datasource/handler/TimeSeriesDataSourceHandler.js]: parser object of this is sometimes undefined, therefore invocation of buildUrl causes exception: 

`TimeSeriesDataSourceHandler.js:35 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'buildUrl')
    at connector.onReconnect (TimeSeriesDataSourceHandler.js:35:68)
    at WebSocketConnector.createReconnection (WebSocketConnector.js:132:64)
    at ws.onclose (WebSocketConnector.js:108:26)`

Comment (nickgaray) [inline source/core/datasource/handler/TimeSeriesDataSourceHandler.js]: The parser object can result in a null reference, this seems like if we get into this situation there is still an error

**Review by nickgaray — CHANGES_REQUESTED** [review]
